# Generated by Django 2.0.13 on 2019-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0005_remove_evaluation_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_list',
            name='book_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
