# Generated by Django 2.0.13 on 2019-11-23 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_system', '0007_remove_fav_list_book_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav_list',
            unique_together={('user', 'book')},
        ),
    ]
